apiVersion: v1
kind: ReplicationController
metadata:
  name: pdf-preview
  labels:
    name: pdf-preview
spec:
  replicas: 1
  selector:
    name: pdf-preview
  template:
    metadata:
      labels:
        name: pdf-preview
    spec:
      containers:
      - name: pdf-preview
        image: ndslabs/pdf-preview:0.9.2
        env:
        - name: RABBITMQ_EXCHANGE
          value: "clowder"
        - name: RABBITMQ_VHOST
          value: "%2F"
        - name: RABBITMQ_QUEUE
          value: "ncsa.pdf.preview"
