apiVersion: v1
kind: ReplicationController
metadata:
  name: speech2text
  labels:
    name: speech2text
spec:
  replicas: 1
  selector:
    name: speech2text
  template:
    metadata:
      labels:
        name: speech2text
    spec:
      containers:
      - name: speech2text
        image: ndslabs/speech2text:0.9.2
        env:
        - name: RABBITMQ_EXCHANGE
          value: "clowder"
        - name: RABBITMQ_VHOST
          value: "%2F"
        - name: RABBITMQ_QUEUE
          value: "speech2text"
